#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <openssl/rsa.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
#include <openssl/bn.h>
#include <curl/curl.h>
#include <json-c/json.h>
#include <jwt-cpp/jwt.h>
#include <microhttpd.h>
#include <signal.h>
#include <unistd.h>
#include "sgx_urts.h"
#include "Enclave_u.h"  // Generated by edger8r

// Global enclave ID
sgx_enclave_id_t global_eid = 0;

// HTTP server related
static struct MHD_Daemon* http_daemon = NULL;
static volatile int server_running = 0;

// Provider enumeration
typedef enum {
    PROVIDER_GOOGLE,
    PROVIDER_GITHUB,
    PROVIDER_APPLE,
    PROVIDER_UNKNOWN
} ProviderType;

// JWT error types
typedef enum {
    JWT_ERROR_NONE = 0,
    JWT_ERROR_INVALID_FORMAT = 1,
    JWT_ERROR_EXPIRED = 2,
    JWT_ERROR_INVALID_SIGNATURE = 3,
    JWT_ERROR_INVALID_ISSUER = 4,
    JWT_ERROR_INVALID_AUDIENCE = 5,
    JWT_ERROR_MISSING_KEY = 6,
    JWT_ERROR_NETWORK = 7,
    JWT_ERROR_NOT_SUPPORTED = 8,
    JWT_ERROR_UNKNOWN_PROVIDER = 9,
    JWT_ERROR = 10
} JWTErrorType;

// Global variable to store last JWT error
static JWTErrorType last_jwt_error = JWT_ERROR_NONE;

// JWT processing result structure
typedef struct {
    char* salt_result;
    JWTErrorType error_type;
    const char* error_message;
} JWTProcessResult;

// Provider configuration structure
typedef struct {
    const char* name;
    const char* jwks_url;
    const char* issuer;
    const char* audience;
    int supported;
} ProviderConfig;

// Get error message for JWT error type
static const char* get_jwt_error_message(JWTErrorType error_type) {
    switch (error_type) {
        case JWT_ERROR_NONE:
            return "No error";
        case JWT_ERROR_INVALID_FORMAT:
            return "Invalid JWT format";
        case JWT_ERROR_EXPIRED:
            return "JWT token has expired";
        case JWT_ERROR_INVALID_SIGNATURE:
            return "Invalid JWT signature";
        case JWT_ERROR_INVALID_ISSUER:
            return "Invalid JWT issuer";
        case JWT_ERROR_INVALID_AUDIENCE:
            return "Invalid JWT audience";
        case JWT_ERROR_MISSING_KEY:
            return "No matching key found for JWT";
        case JWT_ERROR_NETWORK:
            return "Failed to fetch JWKS";
        case JWT_ERROR_NOT_SUPPORTED:
            return "Provider is not supported yet";
        case JWT_ERROR_UNKNOWN_PROVIDER:
            return "Unknown JWK provider";
        case JWT_ERROR:
        default:
            return "JWT verification error";
    }
}

// Constant definitions
static const char* ENCLAVE_FILE = "bin/Enclave.signed.so";
static const int SERVER_PORT = 8080;

// Provider configurations
static const ProviderConfig PROVIDER_CONFIGS[] = {
    {"google", "https://www.googleapis.com/oauth2/v3/certs", "https://accounts.google.com", "560629365517-mt9j9arflcgi35i8hpoptr66qgo1lmfm.apps.googleusercontent.com", 1},
    {"github", "https://token.actions.githubusercontent.com/.well-known/jwks", "", "", 0},
    {"apple", "https://appleid.apple.com/auth/keys", "", "", 0}
};

// HTTP response structure
struct HTTPResponse {
    char* data;
    size_t size;
};

// CURL write callback function
static size_t WriteCallback(void* contents, size_t size, size_t nmemb, struct HTTPResponse* response) {
    size_t total_size = size * nmemb;
    response->data = (char*)realloc(response->data, response->size + total_size + 1);
    if (response->data) {
        memcpy(&(response->data[response->size]), contents, total_size);
        response->size += total_size;
        response->data[response->size] = 0;
    }
    return total_size;
}

// Error handling function
void print_error_message(sgx_status_t ret) {
    printf("SGX Error: 0x%X\n", ret);
}

// Get provider type from string
ProviderType get_provider_type(const char* provider_str) {
    if (!provider_str) return PROVIDER_UNKNOWN;
    
    for (int i = 0; i < 3; i++) {
        if (strcmp(provider_str, PROVIDER_CONFIGS[i].name) == 0) {
            return (ProviderType)i;
        }
    }
    return PROVIDER_UNKNOWN;
}

// Get provider configuration
const ProviderConfig* get_provider_config(ProviderType provider) {
    if (provider >= 0 && provider < 3) {
        return &PROVIDER_CONFIGS[provider];
    }
    return NULL;
}

// Initialize enclave
int initialize_enclave(void) {
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    
    // Create enclave instance
    ret = sgx_create_enclave(
        ENCLAVE_FILE,         // Enclave file
        SGX_DEBUG_FLAG,       // Debug mode
        NULL,                 // Launch token
        NULL,                 // Launch token size
        &global_eid,          // Enclave ID
        NULL                  // Update info
    );
    
    if (ret != SGX_SUCCESS) {
        print_error_message(ret);
        return -1;
    }
    
    printf("Enclave initialized successfully!\n");
    return 0;
}

// Implement OCALL function
void ocall_print_message(const char* message) {
    printf("[OCALL] %s\n", message);
}

// JWT Header structure
typedef struct {
    char* kid;
    char* alg;
    char* typ;
} JWTHeader;

// JWK Key structure
typedef struct {
    char* kid;
    char* n;  // modulus
    char* e;  // exponent
    char* alg;
    char* kty;
    char* use;
} JWKKey;

// JWKS response structure
typedef struct {
    JWKKey* keys;
    int key_count;
} JWKSResponse;

// Base64 URL decode
static int base64url_decode(const char* input, uint8_t* output, int* output_len) {
    const char* chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    int input_len = strlen(input);
    int i = 0, j = 0;
    
    while (i < input_len) {
        uint32_t a = 0, b = 0, c = 0, d = 0;
        
        const char* pos_a = strchr(chars, input[i++]);
        const char* pos_b = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        const char* pos_c = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        const char* pos_d = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        
        if (!pos_a || !pos_b) return -1;
        
        a = pos_a - chars;
        b = pos_b - chars;
        c = pos_c ? (pos_c - chars) : 0;
        d = pos_d ? (pos_d - chars) : 0;
        
        uint32_t combined = (a << 18) | (b << 12) | (c << 6) | d;
        
        if (j < *output_len) output[j++] = (combined >> 16) & 0xFF;
        if (j < *output_len && pos_c) output[j++] = (combined >> 8) & 0xFF;
        if (j < *output_len && pos_d) output[j++] = combined & 0xFF;
    }
    
    *output_len = j;
    return 0;
}

// Parse JWT Header
static int parse_jwt_header(const char* token, JWTHeader* header) {
    // Find first dot
    const char* first_dot = strchr(token, '.');
    if (!first_dot) return -1;
    
    // Find second dot
    const char* second_dot = strchr(first_dot + 1, '.');
    if (!second_dot) return -1;
    
    // Extract header part
    size_t header_len = first_dot - token;
    char* header_b64 = (char*)malloc(header_len + 1);
    strncpy(header_b64, token, header_len);
    header_b64[header_len] = '\0';
    
    // Base64 decode header
    uint8_t* header_data = (uint8_t*)malloc(header_len);
    int header_data_len = header_len;
    
    if (base64url_decode(header_b64, header_data, &header_data_len) != 0) {
        free(header_b64);
        free(header_data);
        return -1;
    }
    
    // Parse JSON
    char* header_json = (char*)malloc(header_data_len + 1);
    memcpy(header_json, header_data, header_data_len);
    header_json[header_data_len] = '\0';
    
    // Simple JSON parsing to extract kid, alg, typ
    const char* kid_start = strstr(header_json, "\"kid\":\"");
    const char* alg_start = strstr(header_json, "\"alg\":\"");
    const char* typ_start = strstr(header_json, "\"typ\":\"");
    
    if (kid_start) {
        kid_start += 7;
        const char* kid_end = strchr(kid_start, '"');
        if (kid_end) {
            int len = kid_end - kid_start;
            header->kid = (char*)malloc(len + 1);
            strncpy(header->kid, kid_start, len);
            header->kid[len] = '\0';
        }
    }
    
    if (alg_start) {
        alg_start += 7;
        const char* alg_end = strchr(alg_start, '"');
        if (alg_end) {
            int len = alg_end - alg_start;
            header->alg = (char*)malloc(len + 1);
            strncpy(header->alg, alg_start, len);
            header->alg[len] = '\0';
        }
    }
    
    if (typ_start) {
        typ_start += 7;
        const char* typ_end = strchr(typ_start, '"');
        if (typ_end) {
            int len = typ_end - typ_start;
            header->typ = (char*)malloc(len + 1);
            strncpy(header->typ, typ_start, len);
            header->typ[len] = '\0';
        }
    }
    
    free(header_b64);
    free(header_data);
    free(header_json);
    
    return 0;
}

// Fetch JWKS from network
static int fetch_jwks(const char* jwks_url, JWKSResponse* jwks) {
    printf("[DEBUG] Fetching JWKS from: %s\n", jwks_url);
    
    CURL* curl;
    CURLcode res;
    struct HTTPResponse response = {0};
    
    curl = curl_easy_init();
    if (!curl) {
        printf("[ERROR] Failed to initialize CURL\n");
        return -1;
    }
    
    curl_easy_setopt(curl, CURLOPT_URL, jwks_url);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10L);
    
    res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
    
    if (res != CURLE_OK) {
        printf("[ERROR] Failed to fetch JWKS: %s\n", curl_easy_strerror(res));
        if (response.data) free(response.data);
        return -1;
    }
    
    if (!response.data) {
        printf("[ERROR] No data received\n");
        return -1;
    }
    
    printf("[DEBUG] JWKS fetched successfully, size: %zu bytes\n", response.size);
    
    // Parse JWKS JSON
    json_object* json = json_tokener_parse(response.data);
    if (!json) {
        printf("[ERROR] Failed to parse JWKS JSON\n");
        free(response.data);
        return -1;
    }
    
    json_object* keys_array;
    if (!json_object_object_get_ex(json, "keys", &keys_array)) {
        printf("[ERROR] No 'keys' array in JWKS\n");
        json_object_put(json);
        free(response.data);
        return -1;
    }
    
    int array_len = json_object_array_length(keys_array);
    printf("[DEBUG] Found %d keys in JWKS\n", array_len);
    
    jwks->keys = (JWKKey*)malloc(array_len * sizeof(JWKKey));
    jwks->key_count = array_len;
    
    for (int i = 0; i < array_len; i++) {
        json_object* key_obj = json_object_array_get_idx(keys_array, i);
        JWKKey* key = &jwks->keys[i];
        
        // Initialize
        key->kid = NULL;
        key->n = NULL;
        key->e = NULL;
        key->alg = NULL;
        key->kty = NULL;
        key->use = NULL;
        
        // Extract fields
        json_object* field;
        if (json_object_object_get_ex(key_obj, "kid", &field)) {
            key->kid = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "n", &field)) {
            key->n = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "e", &field)) {
            key->e = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "alg", &field)) {
            key->alg = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "kty", &field)) {
            key->kty = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "use", &field)) {
            key->use = strdup(json_object_get_string(field));
        }
    }
    
    json_object_put(json);
    free(response.data);
    
    return 0;
}

// Free JWKS memory
static void free_jwks(JWKSResponse* jwks) {
    for (int i = 0; i < jwks->key_count; i++) {
        if (jwks->keys[i].kid) free(jwks->keys[i].kid);
        if (jwks->keys[i].n) free(jwks->keys[i].n);
        if (jwks->keys[i].e) free(jwks->keys[i].e);
        if (jwks->keys[i].alg) free(jwks->keys[i].alg);
        if (jwks->keys[i].kty) free(jwks->keys[i].kty);
        if (jwks->keys[i].use) free(jwks->keys[i].use);
    }
    free(jwks->keys);
}

// Free JWT Header memory
static void free_jwt_header(JWTHeader* header) {
    if (header->kid) free(header->kid);
    if (header->alg) free(header->alg);
    if (header->typ) free(header->typ);
}

// Convert JWK components to PEM format
static std::string jwk_to_pem(const char* n_str, const char* e_str) {
    try {
        // Decode modulus (n)
        uint8_t* n_bytes = (uint8_t*)malloc(4096);
        int n_len = 4096;
        if (base64url_decode(n_str, n_bytes, &n_len) != 0) {
            printf("[ERROR] Failed to decode modulus\n");
            free(n_bytes);
            return "";
        }
        
        // Decode exponent (e)
        uint8_t* e_bytes = (uint8_t*)malloc(64);
        int e_len = 64;
        if (base64url_decode(e_str, e_bytes, &e_len) != 0) {
            printf("[ERROR] Failed to decode exponent\n");
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Create BIGNUM objects
        BIGNUM* n_bn = BN_bin2bn(n_bytes, n_len, NULL);
        BIGNUM* e_bn = BN_bin2bn(e_bytes, e_len, NULL);
        
        if (!n_bn || !e_bn) {
            printf("[ERROR] Failed to create BIGNUM objects\n");
            if (n_bn) BN_free(n_bn);
            if (e_bn) BN_free(e_bn);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Create RSA object
        RSA* rsa = RSA_new();
        if (!rsa) {
            printf("[ERROR] Failed to create RSA object\n");
            BN_free(n_bn);
            BN_free(e_bn);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Set RSA public key
        if (RSA_set0_key(rsa, n_bn, e_bn, NULL) != 1) {
            printf("[ERROR] Failed to set RSA key\n");
            RSA_free(rsa);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Create BIO to write PEM format
        BIO* bio = BIO_new(BIO_s_mem());
        if (!bio) {
            printf("[ERROR] Failed to create BIO\n");
            RSA_free(rsa);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Write public key in PEM format
        if (PEM_write_bio_RSA_PUBKEY(bio, rsa) != 1) {
            printf("[ERROR] Failed to write PEM\n");
            BIO_free(bio);
            RSA_free(rsa);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Get PEM data
        char* pem_data;
        long pem_len = BIO_get_mem_data(bio, &pem_data);
        std::string pem_key(pem_data, pem_len);
        
        // Cleanup resources
        BIO_free(bio);
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        
        return pem_key;
    } catch (const std::exception& e) {
        printf("[ERROR] JWK to PEM conversion failed: %s\n", e.what());
        return "";
    }
}

// Base64 URL decode (for JWK)
static int base64url_decode_jwk(const char* input, uint8_t* output, int* output_len) {
    const char* chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    int input_len = strlen(input);
    int i = 0, j = 0;
    
    // Add padding
    int padding = (4 - (input_len % 4)) % 4;
    char* padded_input = (char*)malloc(input_len + padding + 1);
    strcpy(padded_input, input);
    for (int k = 0; k < padding; k++) {
        strcat(padded_input, "=");
    }
    
    while (i < input_len + padding) {
        if (padded_input[i] == '=') break;
        
        uint32_t a = 0, b = 0, c = 0, d = 0;
        
        const char* pos_a = strchr(chars, padded_input[i++]);
        const char* pos_b = (i < input_len + padding) ? strchr(chars, padded_input[i++]) : NULL;
        const char* pos_c = (i < input_len + padding) ? strchr(chars, padded_input[i++]) : NULL;
        const char* pos_d = (i < input_len + padding) ? strchr(chars, padded_input[i++]) : NULL;
        
        if (!pos_a || !pos_b) {
            free(padded_input);
            return -1;
        }
        
        a = pos_a - chars;
        b = pos_b - chars;
        c = pos_c ? (pos_c - chars) : 0;
        d = pos_d ? (pos_d - chars) : 0;
        
        uint32_t combined = (a << 18) | (b << 12) | (c << 6) | d;
        
        if (j < *output_len) output[j++] = (combined >> 16) & 0xFF;
        if (j < *output_len && pos_c) output[j++] = (combined >> 8) & 0xFF;
        if (j < *output_len && pos_d) output[j++] = combined & 0xFF;
    }
    
    *output_len = j;
    free(padded_input);
    return 0;
}

// Build RSA public key from JWK
static EVP_PKEY* build_rsa_key_from_jwk(const char* n_str, const char* e_str) {
    printf("[DEBUG] Building RSA key from JWK...\n");
    
    // Decode modulus (n)
    uint8_t* n_bytes = (uint8_t*)malloc(4096);
    int n_len = 4096;
    if (base64url_decode_jwk(n_str, n_bytes, &n_len) != 0) {
        printf("[ERROR] Failed to decode modulus\n");
        free(n_bytes);
        return NULL;
    }
    
    // Decode exponent (e)
    uint8_t* e_bytes = (uint8_t*)malloc(64);
    int e_len = 64;
    if (base64url_decode_jwk(e_str, e_bytes, &e_len) != 0) {
        printf("[ERROR] Failed to decode exponent\n");
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Create BIGNUM objects
    BIGNUM* n_bn = BN_bin2bn(n_bytes, n_len, NULL);
    BIGNUM* e_bn = BN_bin2bn(e_bytes, e_len, NULL);
    
    if (!n_bn || !e_bn) {
        printf("[ERROR] Failed to create BIGNUM objects\n");
        if (n_bn) BN_free(n_bn);
        if (e_bn) BN_free(e_bn);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Create RSA object
    RSA* rsa = RSA_new();
    if (!rsa) {
        printf("[ERROR] Failed to create RSA object\n");
        BN_free(n_bn);
        BN_free(e_bn);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Set RSA public key
    if (RSA_set0_key(rsa, n_bn, e_bn, NULL) != 1) {
        printf("[ERROR] Failed to set RSA key\n");
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Create EVP_PKEY
    EVP_PKEY* pkey = EVP_PKEY_new();
    if (!pkey) {
        printf("[ERROR] Failed to create EVP_PKEY\n");
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    if (EVP_PKEY_set1_RSA(pkey, rsa) != 1) {
        printf("[ERROR] Failed to set RSA key in EVP_PKEY\n");
        EVP_PKEY_free(pkey);
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    RSA_free(rsa);
    free(n_bytes);
    free(e_bytes);
    
    printf("[DEBUG] RSA key built successfully\n");
    return pkey;
}

// Verify JWT signature
static int verify_jwt_signature(const char* token, EVP_PKEY* pkey) {
    printf("[DEBUG] Verifying JWT signature...\n");
    
    // Find three parts of JWT
    const char* first_dot = strchr(token, '.');
    if (!first_dot) return -1;
    
    const char* second_dot = strchr(first_dot + 1, '.');
    if (!second_dot) return -1;
    
    // Extract header and payload
    size_t header_len = first_dot - token;
    size_t payload_len = second_dot - (first_dot + 1);
    size_t signature_len = strlen(second_dot + 1);
    
    // Build data to verify (header.payload)
    char* data_to_verify = (char*)malloc(header_len + 1 + payload_len + 1);
    strncpy(data_to_verify, token, header_len);
    data_to_verify[header_len] = '.';
    strncpy(data_to_verify + header_len + 1, first_dot + 1, payload_len);
    data_to_verify[header_len + 1 + payload_len] = '\0';
    
    // Decode signature
    uint8_t* signature = (uint8_t*)malloc(signature_len);
    int sig_len = signature_len;
    if (base64url_decode_jwk(second_dot + 1, signature, &sig_len) != 0) {
        printf("[ERROR] Failed to decode signature\n");
        free(data_to_verify);
        free(signature);
        return -1;
    }
    
    // Create EVP_MD_CTX
    EVP_MD_CTX* md_ctx = EVP_MD_CTX_new();
    if (!md_ctx) {
        printf("[ERROR] Failed to create EVP_MD_CTX\n");
        free(data_to_verify);
        free(signature);
        return -1;
    }
    
    // Initialize verification
    if (EVP_DigestVerifyInit(md_ctx, NULL, EVP_sha256(), NULL, pkey) != 1) {
        printf("[ERROR] Failed to initialize digest verify\n");
        EVP_MD_CTX_free(md_ctx);
        free(data_to_verify);
        free(signature);
        return -1;
    }
    
    // Execute verification
    int result = EVP_DigestVerify(md_ctx, signature, sig_len, 
                                 (const unsigned char*)data_to_verify, 
                                 strlen(data_to_verify));
    
    EVP_MD_CTX_free(md_ctx);
    free(data_to_verify);
    free(signature);
    
    if (result == 1) {
        printf("[DEBUG] JWT signature verification successful\n");
        return 0;
    } else if (result == 0) {
        printf("[ERROR] JWT signature verification failed\n");
        return -1;
    } else {
        printf("[ERROR] JWT signature verification error\n");
        return -1;
    }
}

// Verify JWT for specific provider
int verify_jwt_for_provider(const char* token, ProviderType provider) {
    const ProviderConfig* config = get_provider_config(provider);
    if (!config) {
        printf("[ERROR] Unknown provider\n");
        last_jwt_error = JWT_ERROR_UNKNOWN_PROVIDER;
        return -1;
    }
    
    if (!config->supported) {
        printf("[ERROR] Provider '%s' is not supported yet\n", config->name);
        last_jwt_error = JWT_ERROR_NOT_SUPPORTED;
        return -1;
    }
    
    printf("[DEBUG] Starting %s JWT verification...\n", config->name);
    
    try {
        // Decode JWT
        auto decoded = jwt::decode(std::string(token));
        
        printf("[DEBUG] JWT kid: %s, alg: %s, typ: %s\n", 
               decoded.get_key_id().c_str(),
               decoded.get_algorithm().c_str(), 
               decoded.get_type().c_str());
        
        // Get JWKS
        JWKSResponse jwks = {0};
        if (fetch_jwks(config->jwks_url, &jwks) != 0) {
            printf("[DEBUG] Failed to fetch JWKS\n");
            last_jwt_error = JWT_ERROR_NETWORK;
            return -1;
        }
        
        // Find matching key
        JWKKey* matching_key = NULL;
        std::string kid = decoded.get_key_id();
        for (int i = 0; i < jwks.key_count; i++) {
            if (jwks.keys[i].kid && kid == std::string(jwks.keys[i].kid)) {
                matching_key = &jwks.keys[i];
                break;
            }
        }
        
        if (!matching_key) {
            printf("[DEBUG] No matching key found for kid: %s\n", kid.c_str());
            free_jwks(&jwks);
            last_jwt_error = JWT_ERROR_MISSING_KEY;
            return -1;
        }
        
        printf("[DEBUG] Found matching key: kid=%s, alg=%s, kty=%s\n", 
               matching_key->kid ? matching_key->kid : "NULL",
               matching_key->alg ? matching_key->alg : "NULL",
               matching_key->kty ? matching_key->kty : "NULL");
        
        // Build RSA public key from JWK
        if (matching_key->n && matching_key->e) {
            printf("[DEBUG] Building RSA key from JWK components\n");
            printf("[DEBUG] Modulus (n): %s\n", matching_key->n);
            printf("[DEBUG] Exponent (e): %s\n", matching_key->e);
            
            try {
                // Convert JWK components to PEM format
                std::string pem_key = jwk_to_pem(matching_key->n, matching_key->e);
                if (pem_key.empty()) {
                    printf("[ERROR] Failed to convert JWK to PEM\n");
                    free_jwks(&jwks);
                    last_jwt_error = JWT_ERROR;
                    return -1;
                }
                
                printf("[DEBUG] Converted JWK to PEM format\n");
                printf("[DEBUG] PEM key: %s\n", pem_key.c_str());
                
                // Use jwt-cpp RSA algorithm, following test code approach
                auto rsa_public_key = jwt::algorithm::rs256(pem_key, "", "", "");
                
                // Create verifier
                auto verifier = jwt::verify()
                    .with_issuer(config->issuer)
                    .with_audience(config->audience)
                    .allow_algorithm(rsa_public_key);
                
                // Verify JWT
                verifier.verify(decoded);
                
                printf("[DEBUG] JWT signature verification successful\n");
                
                free_jwks(&jwks);
                last_jwt_error = JWT_ERROR_NONE;
                return 0;
            } catch (const std::exception& e) {
                printf("[ERROR] JWT verification failed: %s\n", e.what());
                free_jwks(&jwks);
                
                // Try to determine error type from exception message
                std::string error_msg = e.what();
                if (error_msg.find("expired") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_EXPIRED;
                } else if (error_msg.find("signature") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_INVALID_SIGNATURE;
                } else if (error_msg.find("issuer") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_INVALID_ISSUER;
                } else if (error_msg.find("audience") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_INVALID_AUDIENCE;
                } else {
                    last_jwt_error = JWT_ERROR;
                }
                return -1;
            }
        } else {
            printf("[ERROR] Missing JWK components (n or e)\n");
            free_jwks(&jwks);
            last_jwt_error = JWT_ERROR;
            return -1;
        }
    } catch (const std::exception& e) {
        printf("[ERROR] %s JWT verification failed: %s\n", config->name, e.what());
        
        // Try to determine error type from exception message
        std::string error_msg = e.what();
        if (error_msg.find("expired") != std::string::npos) {
            last_jwt_error = JWT_ERROR_EXPIRED;
        } else if (error_msg.find("signature") != std::string::npos) {
            last_jwt_error = JWT_ERROR_INVALID_SIGNATURE;
        } else if (error_msg.find("issuer") != std::string::npos) {
            last_jwt_error = JWT_ERROR_INVALID_ISSUER;
        } else if (error_msg.find("audience") != std::string::npos) {
            last_jwt_error = JWT_ERROR_INVALID_AUDIENCE;
        } else {
            last_jwt_error = JWT_ERROR_INVALID_FORMAT;
        }
        return -1;
    }
}

// Process JWT and generate salt
JWTProcessResult process_jwt_token(const char* jwt_token, ProviderType provider) {
    JWTProcessResult result = {NULL, JWT_ERROR_NONE, NULL};
    
    printf("[DEBUG] Processing JWT token for provider: %d\n", provider);
    
    // Verify JWT for the specified provider
    if (verify_jwt_for_provider(jwt_token, provider) != 0) {
        printf("[ERROR] JWT verification failed for provider: %d\n", provider);
        result.error_type = last_jwt_error;
        result.error_message = get_jwt_error_message(last_jwt_error);
        return result;
    } else {
        printf("[DEBUG] JWT verification successful\n");
    }
    
    // Call enclave to process JWT
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    uint8_t output_salt[16] = {0};
    
    ret = jwt_to_salt(global_eid, &ret, 
                     (const uint8_t*)jwt_token, strlen(jwt_token),
                     output_salt);
    
    if (ret != SGX_SUCCESS) {
        printf("[ERROR] ECALL Enclave Failed: %d\n", ret);
        result.error_type = JWT_ERROR;
        result.error_message = "Enclave processing failed";
        return result;
    }
    
    printf("[DEBUG] jwt_to_salt success...\n");
    
    // Convert bytes to decimal number
    unsigned long long decimal_value = 0;
    for (int i = 0; i < 16; i++) {
        decimal_value = (decimal_value << 8) | output_salt[i];
    }
    
    // Convert to string
    result.salt_result = (char*)malloc(64);
    snprintf(result.salt_result, 64, "%llu", decimal_value);
    result.error_type = JWT_ERROR_NONE;
    result.error_message = NULL;
    
    return result;
}

// HTTP request handler function
static enum MHD_Result handle_request(void* cls, struct MHD_Connection* connection,
                         const char* url, const char* method,
                         const char* version, const char* upload_data,
                         size_t* upload_data_size, void** con_cls) {
    
    printf("[HTTP] %s %s\n", method, url);
    
    // Only handle POST requests to /get_salt endpoint
    if (strcmp(method, "POST") == 0 && strcmp(url, "/get_salt") == 0) {
        static char* post_data = NULL;
        static size_t post_data_size = 0;
        
        if (*con_cls == NULL) {
            // First call, initialize
            *con_cls = (void*)1;
            post_data = NULL;
            post_data_size = 0;
            return MHD_YES;
        }
        
        if (upload_data && *upload_data_size > 0) {
            // Receive POST data
            post_data = (char*)realloc(post_data, post_data_size + *upload_data_size + 1);
            memcpy(post_data + post_data_size, upload_data, *upload_data_size);
            post_data_size += *upload_data_size;
            post_data[post_data_size] = '\0';
            *upload_data_size = 0;
            return MHD_YES;
        }
        
        // Process complete POST data
        if (post_data) {
            printf("[DEBUG] Received POST data: %s\n", post_data);
            
            // Parse JSON request body
            json_object* json = json_tokener_parse(post_data);
            if (json == NULL) {
                printf("[ERROR] Invalid JSON\n");
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                
                // Return error response
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Invalid JSON\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            json_object* message_obj;
            json_object* provider_obj;
            const char* jwt_token = NULL;
            const char* provider_str = NULL;
            
            // Get message (JWT token)
            if (json_object_object_get_ex(json, "message", &message_obj)) {
                jwt_token = json_object_get_string(message_obj);
            } else {
                printf("[ERROR] Missing 'message' field in JSON\n");
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Missing 'message' field\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            // Get provider
            if (json_object_object_get_ex(json, "provider", &provider_obj)) {
                provider_str = json_object_get_string(provider_obj);
            } else {
                printf("[ERROR] Missing 'provider' field in JSON\n");
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Missing 'provider' field\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            // Validate provider
            ProviderType provider = get_provider_type(provider_str);
            if (provider == PROVIDER_UNKNOWN) {
                printf("[ERROR] Unknown provider: %s\n", provider_str);
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Unknown provider\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            // Check if provider is supported
            const ProviderConfig* config = get_provider_config(provider);
            if (!config || !config->supported) {
                printf("[ERROR] Provider '%s' is not supported yet\n", config->name);
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Provider '%s' is not supported yet\",\"status\":\"failed\"}", config->name);
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            printf("[DEBUG] Processing JWT: %.100s... with provider: %s\n", jwt_token, provider_str);
            
            JWTProcessResult jwt_result = process_jwt_token(jwt_token, provider);
            if (jwt_result.error_type == JWT_ERROR_NONE && jwt_result.salt_result) {
                    printf("[RESPONSE] %s\n", jwt_result.salt_result);
                    
                    // Create success response
                    char* response_json = (char*)malloc(256);
                    int len = snprintf(response_json, 256, 
                            "{\"salt\":\"%s\",\"status\":\"success\"}", jwt_result.salt_result);
                    
                    printf("[DEBUG] JSON response: %s\n", response_json);
                    printf("[DEBUG] JSON response length: %d\n", len);
                    
                    struct MHD_Response* response = MHD_create_response_from_buffer(
                        len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                    MHD_add_response_header(response, "Content-Type", "application/json");
                    MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                    MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                    MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                    
                    int ret = MHD_queue_response(connection, 200, response);
                    MHD_destroy_response(response);
                    free(jwt_result.salt_result);
                    
                    json_object_put(json);
                    free(post_data);
                    post_data = NULL;
                    post_data_size = 0;
                    return (ret == MHD_YES) ? MHD_YES : MHD_NO;
                } else {
                    printf("[ERROR] JWT processing failed: %s\n", jwt_result.error_message ? jwt_result.error_message : "Unknown error");
                    
                    char* response_json = (char*)malloc(512);
                    int len = snprintf(response_json, 512, 
                            "{\"error\":\"%s\",\"status\":\"failed\"}", 
                            jwt_result.error_message ? jwt_result.error_message : "Failed to process JWT");
                    
                    struct MHD_Response* response = MHD_create_response_from_buffer(
                        len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                    MHD_add_response_header(response, "Content-Type", "application/json");
                    MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                    MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                    MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                    
                    // Set appropriate HTTP status code based on error type
                    int http_status = 500; // Default to internal server error
                    if (jwt_result.error_type == JWT_ERROR_EXPIRED) {
                        http_status = 401; // Unauthorized for expired tokens
                    } else if (jwt_result.error_type == JWT_ERROR_INVALID_SIGNATURE || 
                               jwt_result.error_type == JWT_ERROR_INVALID_ISSUER || 
                               jwt_result.error_type == JWT_ERROR_INVALID_AUDIENCE) {
                        http_status = 401; // Unauthorized for invalid tokens
                    } else if (jwt_result.error_type == JWT_ERROR_INVALID_FORMAT) {
                        http_status = 400; // Bad request for malformed tokens
                    }
                    
                    int ret = MHD_queue_response(connection, http_status, response);
                    MHD_destroy_response(response);
                    
                    // Clean up salt_result if it was allocated
                    if (jwt_result.salt_result) {
                        free(jwt_result.salt_result);
                    }
                    
                    json_object_put(json);
                    free(post_data);
                    post_data = NULL;
                    post_data_size = 0;
                    return (ret == MHD_YES) ? MHD_YES : MHD_NO;
                }
        }
    }
    
    // Handle OPTIONS requests (CORS preflight)
    if (strcmp(method, "OPTIONS") == 0) {
        struct MHD_Response* response = MHD_create_response_from_buffer(0, NULL, MHD_RESPMEM_PERSISTENT);
        MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
        MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
        MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
        int ret = MHD_queue_response(connection, 200, response);
        MHD_destroy_response(response);
        return (ret == MHD_YES) ? MHD_YES : MHD_NO;
    }
    
    // Other requests return 404
    const char* not_found = "{\"error\":\"Not Found\"}";
    struct MHD_Response* response = MHD_create_response_from_buffer(
        strlen(not_found), (void*)not_found, MHD_RESPMEM_PERSISTENT);
    MHD_add_response_header(response, "Content-Type", "application/json");
    int ret = MHD_queue_response(connection, 404, response);
    MHD_destroy_response(response);
    return (ret == MHD_YES) ? MHD_YES : MHD_NO;
}

// Signal handler function
static void signal_handler(int sig) {
    printf("\n[INFO] Received signal %d, shutting down server...\n", sig);
    server_running = 0;
    if (http_daemon) {
        MHD_stop_daemon(http_daemon);
        http_daemon = NULL;
    }
}

// Start HTTP server
static int start_http_server() {
    printf("[INFO] Starting HTTP server on port %d...\n", SERVER_PORT);
    
    http_daemon = MHD_start_daemon(
        MHD_USE_SELECT_INTERNALLY | MHD_USE_DEBUG,
        SERVER_PORT,
        NULL, NULL,
        &handle_request, NULL,
        MHD_OPTION_END
    );
    
    if (http_daemon == NULL) {
        printf("[ERROR] Failed to start HTTP server\n");
        return -1;
    }
    
    printf("[INFO] HTTP server started successfully on port %d\n", SERVER_PORT);
    printf("[INFO] Send POST requests to http://localhost:%d/get_salt\n", SERVER_PORT);
    printf("[INFO] Press Ctrl+C to stop the server\n");
    
    server_running = 1;
    return 0;
}

int main(int argc, char* argv[]) {
    printf("=== SGX JWT Salt Generator HTTP Server ===\n\n");
    
    // Set up signal handling
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);
    
    // Initialize CURL
    curl_global_init(CURL_GLOBAL_DEFAULT);
    
    // Initialize enclave
    if (initialize_enclave() < 0) {
        printf("Failed to initialize enclave\n");
        curl_global_cleanup();
        return -1;
    }
    
    // Start HTTP server
    if (start_http_server() < 0) {
        printf("Failed to start HTTP server\n");
        sgx_destroy_enclave(global_eid);
        curl_global_cleanup();
        return -1;
    }
    
    // Main loop - keep server running
    while (server_running) {
        sleep(1);
    }
    
    // Cleanup resources
    printf("\n[INFO] Shutting down...\n");
    if (http_daemon) {
        MHD_stop_daemon(http_daemon);
        http_daemon = NULL;
    }
    sgx_destroy_enclave(global_eid);
    curl_global_cleanup();
    
    printf("Enclave destroyed successfully!\n");
    return 0;
}