#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <openssl/rsa.h>
#include <openssl/pem.h>
#include <openssl/bio.h>
#include <openssl/bn.h>
#include <curl/curl.h>
#include <json-c/json.h>
#include <jwt-cpp/jwt.h>
#include <microhttpd.h>
#include <signal.h>
#include <unistd.h>
#include "sgx_urts.h"
#include "Enclave_u.h"  // Generated by edger8r

// Global enclave ID
sgx_enclave_id_t global_eid = 0;

// HTTP server related
static struct MHD_Daemon* http_daemon = NULL;
static volatile int server_running = 0;

// Provider enumeration
typedef enum {
    PROVIDER_GOOGLE,
    PROVIDER_GITHUB,
    PROVIDER_APPLE,
    PROVIDER_UNKNOWN
} ProviderType;

// JWT error types
typedef enum {
    JWT_ERROR_NONE = 0,
    JWT_ERROR_INVALID_FORMAT = 1,
    JWT_ERROR_EXPIRED = 2,
    JWT_ERROR_INVALID_SIGNATURE = 3,
    JWT_ERROR_INVALID_ISSUER = 4,
    JWT_ERROR_INVALID_AUDIENCE = 5,
    JWT_ERROR_MISSING_KEY = 6,
    JWT_ERROR_NETWORK = 7,
    JWT_ERROR_NOT_SUPPORTED = 8,
    JWT_ERROR_UNKNOWN_PROVIDER = 9,
    JWT_ERROR = 10
} JWTErrorType;

// Global variable to store last JWT error
static JWTErrorType last_jwt_error = JWT_ERROR_NONE;

// JWT processing result structure
typedef struct {
    char* salt_result;
    JWTErrorType error_type;
    const char* error_message;
} JWTProcessResult;

// Provider configuration structure
typedef struct {
    const char* name;
    const char* jwks_url;
    const char* issuer;
    const char* audience;
    int supported;
} ProviderConfig;

// Get error message for JWT error type
static const char* get_jwt_error_message(JWTErrorType error_type) {
    switch (error_type) {
        case JWT_ERROR_NONE:
            return "No error";
        case JWT_ERROR_INVALID_FORMAT:
            return "Invalid JWT format";
        case JWT_ERROR_EXPIRED:
            return "JWT token has expired";
        case JWT_ERROR_INVALID_SIGNATURE:
            return "Invalid JWT signature";
        case JWT_ERROR_INVALID_ISSUER:
            return "Invalid JWT issuer";
        case JWT_ERROR_INVALID_AUDIENCE:
            return "Invalid JWT audience";
        case JWT_ERROR_MISSING_KEY:
            return "No matching key found for JWT";
        case JWT_ERROR_NETWORK:
            return "Failed to fetch JWKS";
        case JWT_ERROR_NOT_SUPPORTED:
            return "Provider is not supported yet";
        case JWT_ERROR_UNKNOWN_PROVIDER:
            return "Unknown JWK provider";
        case JWT_ERROR:
        default:
            return "JWT verification error";
    }
}

// Constant definitions
static const char* ENCLAVE_FILE = "enclave.signed.so";
static const int SERVER_PORT = 8080;

// Provider configurations
static const ProviderConfig PROVIDER_CONFIGS[] = {
    {"google", "https://www.googleapis.com/oauth2/v3/certs", "https://accounts.google.com", "560629365517-mt9j9arflcgi35i8hpoptr66qgo1lmfm.apps.googleusercontent.com", 1},
    {"github", "https://token.actions.githubusercontent.com/.well-known/jwks", "", "", 0},
    {"apple", "https://appleid.apple.com/auth/keys", "", "", 0}
};

// HTTP response structure
struct HTTPResponse {
    char* data;
    size_t size;
};

// CURL write callback function
static size_t WriteCallback(void* contents, size_t size, size_t nmemb, struct HTTPResponse* response) {
    size_t total_size = size * nmemb;
    response->data = (char*)realloc(response->data, response->size + total_size + 1);
    if (response->data) {
        memcpy(&(response->data[response->size]), contents, total_size);
        response->size += total_size;
        response->data[response->size] = 0;
    }
    return total_size;
}

// Error handling function
void print_error_message(sgx_status_t ret) {
    printf("SGX Error: 0x%X\n", ret);
}

// Get provider type from string
ProviderType get_provider_type(const char* provider_str) {
    if (!provider_str) return PROVIDER_UNKNOWN;
    
    for (int i = 0; i < 3; i++) {
        if (strcmp(provider_str, PROVIDER_CONFIGS[i].name) == 0) {
            return (ProviderType)i;
        }
    }
    return PROVIDER_UNKNOWN;
}

// Get provider configuration
const ProviderConfig* get_provider_config(ProviderType provider) {
    if (provider >= 0 && provider < 3) {
        return &PROVIDER_CONFIGS[provider];
    }
    return NULL;
}

// Initialize enclave
int initialize_enclave(void) {
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    
    // Create enclave instance
    ret = sgx_create_enclave(
        ENCLAVE_FILE,         // Enclave file
        SGX_DEBUG_FLAG,       // Debug mode
        NULL,                 // Launch token
        NULL,                 // Launch token size
        &global_eid,          // Enclave ID
        NULL                  // Update info
    );
    
    if (ret != SGX_SUCCESS) {
        print_error_message(ret);
        return -1;
    }
    
    printf("Enclave initialized successfully!\n");
    return 0;
}

// Implement OCALL function
void ocall_print_message(const char* message) {
    printf("[OCALL] %s\n", message);
}

// JWT Header structure
typedef struct {
    char* kid;
    char* alg;
    char* typ;
} JWTHeader;

// JWK Key structure
typedef struct {
    char* kid;
    char* n;  // modulus
    char* e;  // exponent
    char* alg;
    char* kty;
    char* use;
} JWKKey;

// JWKS response structure
typedef struct {
    JWKKey* keys;
    int key_count;
} JWKSResponse;

// Base64 URL decode
static int base64url_decode(const char* input, uint8_t* output, int* output_len) {
    const char* chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    int input_len = strlen(input);
    int i = 0, j = 0;
    
    while (i < input_len) {
        uint32_t a = 0, b = 0, c = 0, d = 0;
        
        const char* pos_a = strchr(chars, input[i++]);
        const char* pos_b = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        const char* pos_c = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        const char* pos_d = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        
        if (!pos_a || !pos_b) return -1;
        
        a = pos_a - chars;
        b = pos_b - chars;
        c = pos_c ? (pos_c - chars) : 0;
        d = pos_d ? (pos_d - chars) : 0;
        
        uint32_t combined = (a << 18) | (b << 12) | (c << 6) | d;
        
        if (j < *output_len) output[j++] = (combined >> 16) & 0xFF;
        if (j < *output_len && pos_c) output[j++] = (combined >> 8) & 0xFF;
        if (j < *output_len && pos_d) output[j++] = combined & 0xFF;
    }
    
    *output_len = j;
    return 0;
}


// Fetch JWKS from network
static int fetch_jwks(const char* jwks_url, JWKSResponse* jwks) {
    printf("[DEBUG] Fetching JWKS from: %s\n", jwks_url);
    
    CURL* curl;
    CURLcode res;
    struct HTTPResponse response = {0};
    
    curl = curl_easy_init();
    if (!curl) {
        printf("[ERROR] Failed to initialize CURL\n");
        return -1;
    }
    
    curl_easy_setopt(curl, CURLOPT_URL, jwks_url);
    curl_easy_setopt(curl, CURLOPT_WRITEFUNCTION, WriteCallback);
    curl_easy_setopt(curl, CURLOPT_WRITEDATA, &response);
    curl_easy_setopt(curl, CURLOPT_TIMEOUT, 10L);
    
    res = curl_easy_perform(curl);
    curl_easy_cleanup(curl);
    
    if (res != CURLE_OK) {
        printf("[ERROR] Failed to fetch JWKS: %s\n", curl_easy_strerror(res));
        if (response.data) free(response.data);
        return -1;
    }
    
    if (!response.data) {
        printf("[ERROR] No data received\n");
        return -1;
    }
    
    printf("[DEBUG] JWKS fetched successfully, size: %zu bytes\n", response.size);
    
    // Parse JWKS JSON
    json_object* json = json_tokener_parse(response.data);
    if (!json) {
        printf("[ERROR] Failed to parse JWKS JSON\n");
        free(response.data);
        return -1;
    }
    
    json_object* keys_array;
    if (!json_object_object_get_ex(json, "keys", &keys_array)) {
        printf("[ERROR] No 'keys' array in JWKS\n");
        json_object_put(json);
        free(response.data);
        return -1;
    }
    
    int array_len = json_object_array_length(keys_array);
    printf("[DEBUG] Found %d keys in JWKS\n", array_len);
    
    jwks->keys = (JWKKey*)malloc(array_len * sizeof(JWKKey));
    jwks->key_count = array_len;
    
    for (int i = 0; i < array_len; i++) {
        json_object* key_obj = json_object_array_get_idx(keys_array, i);
        JWKKey* key = &jwks->keys[i];
        
        // Initialize
        key->kid = NULL;
        key->n = NULL;
        key->e = NULL;
        key->alg = NULL;
        key->kty = NULL;
        key->use = NULL;
        
        // Extract fields
        json_object* field;
        if (json_object_object_get_ex(key_obj, "kid", &field)) {
            key->kid = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "n", &field)) {
            key->n = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "e", &field)) {
            key->e = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "alg", &field)) {
            key->alg = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "kty", &field)) {
            key->kty = strdup(json_object_get_string(field));
        }
        if (json_object_object_get_ex(key_obj, "use", &field)) {
            key->use = strdup(json_object_get_string(field));
        }
    }
    
    json_object_put(json);
    free(response.data);
    
    return 0;
}

// Free JWKS memory
static void free_jwks(JWKSResponse* jwks) {
    for (int i = 0; i < jwks->key_count; i++) {
        if (jwks->keys[i].kid) free(jwks->keys[i].kid);
        if (jwks->keys[i].n) free(jwks->keys[i].n);
        if (jwks->keys[i].e) free(jwks->keys[i].e);
        if (jwks->keys[i].alg) free(jwks->keys[i].alg);
        if (jwks->keys[i].kty) free(jwks->keys[i].kty);
        if (jwks->keys[i].use) free(jwks->keys[i].use);
    }
    free(jwks->keys);
}

// Free JWT Header memory
static void free_jwt_header(JWTHeader* header) {
    if (header->kid) free(header->kid);
    if (header->alg) free(header->alg);
    if (header->typ) free(header->typ);
}

// Convert JWK components to PEM format
static std::string jwk_to_pem(const char* n_str, const char* e_str) {
    try {
        // Decode modulus (n)
        uint8_t* n_bytes = (uint8_t*)malloc(4096);
        int n_len = 4096;
        if (base64url_decode(n_str, n_bytes, &n_len) != 0) {
            printf("[ERROR] Failed to decode modulus\n");
            free(n_bytes);
            return "";
        }
        
        // Decode exponent (e)
        uint8_t* e_bytes = (uint8_t*)malloc(64);
        int e_len = 64;
        if (base64url_decode(e_str, e_bytes, &e_len) != 0) {
            printf("[ERROR] Failed to decode exponent\n");
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Create BIGNUM objects
        BIGNUM* n_bn = BN_bin2bn(n_bytes, n_len, NULL);
        BIGNUM* e_bn = BN_bin2bn(e_bytes, e_len, NULL);
        
        if (!n_bn || !e_bn) {
            printf("[ERROR] Failed to create BIGNUM objects\n");
            if (n_bn) BN_free(n_bn);
            if (e_bn) BN_free(e_bn);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Create RSA object
        RSA* rsa = RSA_new();
        if (!rsa) {
            printf("[ERROR] Failed to create RSA object\n");
            BN_free(n_bn);
            BN_free(e_bn);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Set RSA public key
        if (RSA_set0_key(rsa, n_bn, e_bn, NULL) != 1) {
            printf("[ERROR] Failed to set RSA key\n");
            RSA_free(rsa);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Create BIO to write PEM format
        BIO* bio = BIO_new(BIO_s_mem());
        if (!bio) {
            printf("[ERROR] Failed to create BIO\n");
            RSA_free(rsa);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Write public key in PEM format
        if (PEM_write_bio_RSA_PUBKEY(bio, rsa) != 1) {
            printf("[ERROR] Failed to write PEM\n");
            BIO_free(bio);
            RSA_free(rsa);
            free(n_bytes);
            free(e_bytes);
            return "";
        }
        
        // Get PEM data
        char* pem_data;
        long pem_len = BIO_get_mem_data(bio, &pem_data);
        std::string pem_key(pem_data, pem_len);
        
        // Cleanup resources
        BIO_free(bio);
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        
        return pem_key;
    } catch (const std::exception& e) {
        printf("[ERROR] JWK to PEM conversion failed: %s\n", e.what());
        return "";
    }
}

// Base64 URL decode (for JWK)
static int base64url_decode_jwk(const char* input, uint8_t* output, int* output_len) {
    const char* chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    int input_len = strlen(input);
    int i = 0, j = 0;
    
    // Add padding
    int padding = (4 - (input_len % 4)) % 4;
    char* padded_input = (char*)malloc(input_len + padding + 1);
    strcpy(padded_input, input);
    for (int k = 0; k < padding; k++) {
        strcat(padded_input, "=");
    }
    
    while (i < input_len + padding) {
        if (padded_input[i] == '=') break;
        
        uint32_t a = 0, b = 0, c = 0, d = 0;
        
        const char* pos_a = strchr(chars, padded_input[i++]);
        const char* pos_b = (i < input_len + padding) ? strchr(chars, padded_input[i++]) : NULL;
        const char* pos_c = (i < input_len + padding) ? strchr(chars, padded_input[i++]) : NULL;
        const char* pos_d = (i < input_len + padding) ? strchr(chars, padded_input[i++]) : NULL;
        
        if (!pos_a || !pos_b) {
            free(padded_input);
            return -1;
        }
        
        a = pos_a - chars;
        b = pos_b - chars;
        c = pos_c ? (pos_c - chars) : 0;
        d = pos_d ? (pos_d - chars) : 0;
        
        uint32_t combined = (a << 18) | (b << 12) | (c << 6) | d;
        
        if (j < *output_len) output[j++] = (combined >> 16) & 0xFF;
        if (j < *output_len && pos_c) output[j++] = (combined >> 8) & 0xFF;
        if (j < *output_len && pos_d) output[j++] = combined & 0xFF;
    }
    
    *output_len = j;
    free(padded_input);
    return 0;
}

// Build RSA public key from JWK
static EVP_PKEY* build_rsa_key_from_jwk(const char* n_str, const char* e_str) {
    printf("[DEBUG] Building RSA key from JWK...\n");
    
    // Decode modulus (n)
    uint8_t* n_bytes = (uint8_t*)malloc(4096);
    int n_len = 4096;
    if (base64url_decode_jwk(n_str, n_bytes, &n_len) != 0) {
        printf("[ERROR] Failed to decode modulus\n");
        free(n_bytes);
        return NULL;
    }
    
    // Decode exponent (e)
    uint8_t* e_bytes = (uint8_t*)malloc(64);
    int e_len = 64;
    if (base64url_decode_jwk(e_str, e_bytes, &e_len) != 0) {
        printf("[ERROR] Failed to decode exponent\n");
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Create BIGNUM objects
    BIGNUM* n_bn = BN_bin2bn(n_bytes, n_len, NULL);
    BIGNUM* e_bn = BN_bin2bn(e_bytes, e_len, NULL);
    
    if (!n_bn || !e_bn) {
        printf("[ERROR] Failed to create BIGNUM objects\n");
        if (n_bn) BN_free(n_bn);
        if (e_bn) BN_free(e_bn);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Create RSA object
    RSA* rsa = RSA_new();
    if (!rsa) {
        printf("[ERROR] Failed to create RSA object\n");
        BN_free(n_bn);
        BN_free(e_bn);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Set RSA public key
    if (RSA_set0_key(rsa, n_bn, e_bn, NULL) != 1) {
        printf("[ERROR] Failed to set RSA key\n");
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    // Create EVP_PKEY
    EVP_PKEY* pkey = EVP_PKEY_new();
    if (!pkey) {
        printf("[ERROR] Failed to create EVP_PKEY\n");
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    if (EVP_PKEY_set1_RSA(pkey, rsa) != 1) {
        printf("[ERROR] Failed to set RSA key in EVP_PKEY\n");
        EVP_PKEY_free(pkey);
        RSA_free(rsa);
        free(n_bytes);
        free(e_bytes);
        return NULL;
    }
    
    RSA_free(rsa);
    free(n_bytes);
    free(e_bytes);
    
    printf("[DEBUG] RSA key built successfully\n");
    return pkey;
}



// Verify JWT for specific provider
int verify_jwt_for_provider(const char* token, ProviderType provider) {
    const ProviderConfig* config = get_provider_config(provider);
    if (!config) {
        printf("[ERROR] Unknown provider\n");
        last_jwt_error = JWT_ERROR_UNKNOWN_PROVIDER;
        return -1;
    }
    
    if (!config->supported) {
        printf("[ERROR] Provider '%s' is not supported yet\n", config->name);
        last_jwt_error = JWT_ERROR_NOT_SUPPORTED;
        return -1;
    }
    
    printf("[DEBUG] Starting %s JWT verification...\n", config->name);
    
    try {
        // Decode JWT
        auto decoded = jwt::decode(std::string(token));
        
        printf("[DEBUG] JWT kid: %s, alg: %s, typ: %s\n", 
               decoded.get_key_id().c_str(),
               decoded.get_algorithm().c_str(), 
               decoded.get_type().c_str());
        
        // Get JWKS
        JWKSResponse jwks = {0};
        if (fetch_jwks(config->jwks_url, &jwks) != 0) {
            printf("[DEBUG] Failed to fetch JWKS\n");
            last_jwt_error = JWT_ERROR_NETWORK;
            return -1;
        }
        
        // Find matching key
        JWKKey* matching_key = NULL;
        std::string kid = decoded.get_key_id();
        for (int i = 0; i < jwks.key_count; i++) {
            if (jwks.keys[i].kid && kid == std::string(jwks.keys[i].kid)) {
                matching_key = &jwks.keys[i];
                break;
            }
        }
        
        if (!matching_key) {
            printf("[DEBUG] No matching key found for kid: %s\n", kid.c_str());
            free_jwks(&jwks);
            last_jwt_error = JWT_ERROR_MISSING_KEY;
            return -1;
        }
        
        printf("[DEBUG] Found matching key: kid=%s, alg=%s, kty=%s\n", 
               matching_key->kid ? matching_key->kid : "NULL",
               matching_key->alg ? matching_key->alg : "NULL",
               matching_key->kty ? matching_key->kty : "NULL");
        
        // Build RSA public key from JWK
        if (matching_key->n && matching_key->e) {
            printf("[DEBUG] Building RSA key from JWK components\n");
            printf("[DEBUG] Modulus (n): %s\n", matching_key->n);
            printf("[DEBUG] Exponent (e): %s\n", matching_key->e);
            
            try {
                // Convert JWK components to PEM format
                std::string pem_key = jwk_to_pem(matching_key->n, matching_key->e);
                if (pem_key.empty()) {
                    printf("[ERROR] Failed to convert JWK to PEM\n");
                    free_jwks(&jwks);
                    last_jwt_error = JWT_ERROR;
                    return -1;
                }
                
                printf("[DEBUG] Converted JWK to PEM format\n");
                printf("[DEBUG] PEM key: %s\n", pem_key.c_str());
                
                // Use jwt-cpp RSA algorithm, following test code approach
                auto rsa_public_key = jwt::algorithm::rs256(pem_key, "", "", "");
                
                // Create verifier (skip expiration time validation by setting large leeway)
                auto verifier = jwt::verify()
                    .with_issuer(config->issuer)
                    .with_audience(config->audience)
                    .allow_algorithm(rsa_public_key);
                
                // Verify JWT
                verifier.verify(decoded);
                
                printf("[DEBUG] JWT signature verification successful\n");
                
                free_jwks(&jwks);
                last_jwt_error = JWT_ERROR_NONE;
                return 0;
            } catch (const std::exception& e) {
                printf("[ERROR] JWT verification failed: %s\n", e.what());
                free_jwks(&jwks);
                
                // Try to determine error type from exception message
                std::string error_msg = e.what();
                if (error_msg.find("expired") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_EXPIRED;
                } else if (error_msg.find("signature") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_INVALID_SIGNATURE;
                } else if (error_msg.find("issuer") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_INVALID_ISSUER;
                } else if (error_msg.find("audience") != std::string::npos) {
                    last_jwt_error = JWT_ERROR_INVALID_AUDIENCE;
                } else {
                    last_jwt_error = JWT_ERROR;
                }
                return -1;
            }
        } else {
            printf("[ERROR] Missing JWK components (n or e)\n");
            free_jwks(&jwks);
            last_jwt_error = JWT_ERROR;
            return -1;
        }
    } catch (const std::exception& e) {
        printf("[ERROR] %s JWT verification failed: %s\n", config->name, e.what());
        
        // Try to determine error type from exception message
        std::string error_msg = e.what();
        if (error_msg.find("expired") != std::string::npos) {
            last_jwt_error = JWT_ERROR_EXPIRED;
        } else if (error_msg.find("signature") != std::string::npos) {
            last_jwt_error = JWT_ERROR_INVALID_SIGNATURE;
        } else if (error_msg.find("issuer") != std::string::npos) {
            last_jwt_error = JWT_ERROR_INVALID_ISSUER;
        } else if (error_msg.find("audience") != std::string::npos) {
            last_jwt_error = JWT_ERROR_INVALID_AUDIENCE;
        } else {
            last_jwt_error = JWT_ERROR_INVALID_FORMAT;
        }
        return -1;
    }
}

// Process JWT and generate salt
JWTProcessResult process_jwt_token(const char* jwt_token, ProviderType provider) {
    JWTProcessResult result = {NULL, JWT_ERROR_NONE, NULL};
    
    printf("[DEBUG] Processing JWT token for provider: %d\n", provider);
    
    // Verify JWT for the specified provider
    if (verify_jwt_for_provider(jwt_token, provider) != 0) {
        printf("[ERROR] JWT verification failed for provider: %d\n", provider);
        result.error_type = last_jwt_error;
        result.error_message = get_jwt_error_message(last_jwt_error);
        return result;
    } else {
        printf("[DEBUG] JWT verification successful\n");
    }
    
    // Call enclave to process JWT
    sgx_status_t ret = SGX_ERROR_UNEXPECTED;
    uint8_t output_salt[16] = {0};
    
    ret = jwt_to_salt(global_eid, &ret, 
                     (const uint8_t*)jwt_token, strlen(jwt_token),
                     output_salt);
    
    if (ret != SGX_SUCCESS) {
        printf("[ERROR] ECALL Enclave Failed: %d\n", ret);
        result.error_type = JWT_ERROR;
        result.error_message = "Enclave processing failed";
        return result;
    }
    
    printf("[DEBUG] jwt_to_salt success...\n");
    
    // Convert bytes to decimal number
    unsigned long long decimal_value = 0;
    for (int i = 0; i < 16; i++) {
        decimal_value = (decimal_value << 8) | output_salt[i];
    }
    
    // Convert to string
    result.salt_result = (char*)malloc(64);
    snprintf(result.salt_result, 64, "%llu", decimal_value);
    result.error_type = JWT_ERROR_NONE;
    result.error_message = NULL;
    
    return result;
}

// HTTP request handler function
static int handle_request(void* cls, struct MHD_Connection* connection,
                         const char* url, const char* method,
                         const char* version, const char* upload_data,
                         size_t* upload_data_size, void** con_cls) {
    
    printf("[HTTP] %s %s\n", method, url);
    
    // Only handle POST requests to /get_salt endpoint
    if (strcmp(method, "POST") == 0 && strcmp(url, "/get_salt") == 0) {
        static char* post_data = NULL;
        static size_t post_data_size = 0;
        
        if (*con_cls == NULL) {
            // First call, initialize
            *con_cls = (void*)1;
            post_data = NULL;
            post_data_size = 0;
            return MHD_YES;
        }
        
        if (upload_data && *upload_data_size > 0) {
            // Receive POST data
            post_data = (char*)realloc(post_data, post_data_size + *upload_data_size + 1);
            memcpy(post_data + post_data_size, upload_data, *upload_data_size);
            post_data_size += *upload_data_size;
            post_data[post_data_size] = '\0';
            *upload_data_size = 0;
            return MHD_YES;
        }
        
        // Process complete POST data
        if (post_data) {
            printf("[DEBUG] Received POST data: %s\n", post_data);
            
            // Parse JSON request body
            json_object* json = json_tokener_parse(post_data);
            if (json == NULL) {
                printf("[ERROR] Invalid JSON\n");
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                
                // Return error response
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Invalid JSON\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            json_object* message_obj;
            json_object* provider_obj;
            const char* jwt_token = NULL;
            const char* provider_str = NULL;
            
            // Get message (JWT token)
            if (json_object_object_get_ex(json, "message", &message_obj)) {
                jwt_token = json_object_get_string(message_obj);
            } else {
                printf("[ERROR] Missing 'message' field in JSON\n");
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Missing 'message' field\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            // Get provider
            if (json_object_object_get_ex(json, "provider", &provider_obj)) {
                provider_str = json_object_get_string(provider_obj);
            } else {
                printf("[ERROR] Missing 'provider' field in JSON\n");
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Missing 'provider' field\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            // Validate provider
            ProviderType provider = get_provider_type(provider_str);
            if (provider == PROVIDER_UNKNOWN) {
                printf("[ERROR] Unknown provider: %s\n", provider_str);
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Unknown provider\",\"status\":\"failed\"}");
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            // Check if provider is supported
            const ProviderConfig* config = get_provider_config(provider);
            if (!config || !config->supported) {
                printf("[ERROR] Provider '%s' is not supported yet\n", config->name);
                char* response_json = (char*)malloc(256);
                int len = snprintf(response_json, 256, 
                        "{\"error\":\"Provider '%s' is not supported yet\",\"status\":\"failed\"}", config->name);
                
                struct MHD_Response* response = MHD_create_response_from_buffer(
                    len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                MHD_add_response_header(response, "Content-Type", "application/json");
                MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                int ret = MHD_queue_response(connection, 400, response);
                MHD_destroy_response(response);
                
                json_object_put(json);
                free(post_data);
                post_data = NULL;
                post_data_size = 0;
                return (ret == MHD_YES) ? MHD_YES : MHD_NO;
            }
            
            printf("[DEBUG] Processing JWT: %.100s... with provider: %s\n", jwt_token, provider_str);
            
            JWTProcessResult jwt_result = process_jwt_token(jwt_token, provider);
            if (jwt_result.error_type == JWT_ERROR_NONE && jwt_result.salt_result) {
                    printf("[RESPONSE] %s\n", jwt_result.salt_result);
                    
                    // Create success response
                    char* response_json = (char*)malloc(256);
                    int len = snprintf(response_json, 256, 
                            "{\"salt\":\"%s\",\"status\":\"success\"}", jwt_result.salt_result);
                    
                    printf("[DEBUG] JSON response: %s\n", response_json);
                    printf("[DEBUG] JSON response length: %d\n", len);
                    
                    struct MHD_Response* response = MHD_create_response_from_buffer(
                        len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                    MHD_add_response_header(response, "Content-Type", "application/json");
                    MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                    MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                    MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                    
                    int ret = MHD_queue_response(connection, 200, response);
                    MHD_destroy_response(response);
                    free(jwt_result.salt_result);
                    
                    json_object_put(json);
                    free(post_data);
                    post_data = NULL;
                    post_data_size = 0;
                    return (ret == MHD_YES) ? MHD_YES : MHD_NO;
                } else {
                    printf("[ERROR] JWT processing failed: %s\n", jwt_result.error_message ? jwt_result.error_message : "Unknown error");
                    
                    char* response_json = (char*)malloc(512);
                    int len = snprintf(response_json, 512, 
                            "{\"error\":\"%s\",\"status\":\"failed\"}", 
                            jwt_result.error_message ? jwt_result.error_message : "Failed to process JWT");
                    
                    struct MHD_Response* response = MHD_create_response_from_buffer(
                        len, (void*)response_json, MHD_RESPMEM_MUST_FREE);
                    MHD_add_response_header(response, "Content-Type", "application/json");
                    MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
                    MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
                    MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
                    
                    // Set appropriate HTTP status code based on error type
                    int http_status = 500; // Default to internal server error
                    if (jwt_result.error_type == JWT_ERROR_EXPIRED) {
                        http_status = 401; // Unauthorized for expired tokens
                    } else if (jwt_result.error_type == JWT_ERROR_INVALID_SIGNATURE || 
                               jwt_result.error_type == JWT_ERROR_INVALID_ISSUER || 
                               jwt_result.error_type == JWT_ERROR_INVALID_AUDIENCE) {
                        http_status = 401; // Unauthorized for invalid tokens
                    } else if (jwt_result.error_type == JWT_ERROR_INVALID_FORMAT) {
                        http_status = 400; // Bad request for malformed tokens
                    }
                    
                    int ret = MHD_queue_response(connection, http_status, response);
                    MHD_destroy_response(response);
                    
                    // Clean up salt_result if it was allocated
                    if (jwt_result.salt_result) {
                        free(jwt_result.salt_result);
                    }
                    
                    json_object_put(json);
                    free(post_data);
                    post_data = NULL;
                    post_data_size = 0;
                    return (ret == MHD_YES) ? MHD_YES : MHD_NO;
                }
        }
    }
    
    // Handle OPTIONS requests (CORS preflight)
    if (strcmp(method, "OPTIONS") == 0) {
        struct MHD_Response* response = MHD_create_response_from_buffer(0, NULL, MHD_RESPMEM_PERSISTENT);
        MHD_add_response_header(response, "Access-Control-Allow-Origin", "*");
        MHD_add_response_header(response, "Access-Control-Allow-Methods", "POST, OPTIONS");
        MHD_add_response_header(response, "Access-Control-Allow-Headers", "Content-Type");
        int ret = MHD_queue_response(connection, 200, response);
        MHD_destroy_response(response);
        return (ret == MHD_YES) ? MHD_YES : MHD_NO;
    }
    
    // Other requests return 404
    const char* not_found = "{\"error\":\"Not Found\"}";
    struct MHD_Response* response = MHD_create_response_from_buffer(
        strlen(not_found), (void*)not_found, MHD_RESPMEM_PERSISTENT);
    MHD_add_response_header(response, "Content-Type", "application/json");
    int ret = MHD_queue_response(connection, 404, response);
    MHD_destroy_response(response);
    return (ret == MHD_YES) ? MHD_YES : MHD_NO;
}

// Signal handler function
static void signal_handler(int sig) {
    printf("\n[INFO] Received signal %d, shutting down server...\n", sig);
    server_running = 0;
    if (http_daemon) {
        MHD_stop_daemon(http_daemon);
        http_daemon = NULL;
    }
}

// Start HTTP server
static int start_http_server() {
    printf("[INFO] Starting HTTP server on port %d...\n", SERVER_PORT);
    
    http_daemon = MHD_start_daemon(
        MHD_USE_SELECT_INTERNALLY | MHD_USE_DEBUG,
        SERVER_PORT,
        NULL, NULL,
        &handle_request, NULL,
        MHD_OPTION_END
    );
    
    if (http_daemon == NULL) {
        printf("[ERROR] Failed to start HTTP server\n");
        return -1;
    }
    
    printf("[INFO] HTTP server started successfully on port %d\n", SERVER_PORT);
    printf("[INFO] Send POST requests to http://localhost:%d/get_salt\n", SERVER_PORT);
    printf("[INFO] Press Ctrl+C to stop the server\n");
    
    server_running = 1;
    return 0;
}

// Test functions
#ifdef TEST_MODE
// Test get_provider_type function
int test_get_provider_type() {
    printf("\n=== Testing get_provider_type ===\n");
    
    // Test valid providers
    if (get_provider_type("google") != PROVIDER_GOOGLE) {
        printf("FAIL: google should return PROVIDER_GOOGLE\n");
        return -1;
    }
    if (get_provider_type("github") != PROVIDER_GITHUB) {
        printf("FAIL: github should return PROVIDER_GITHUB\n");
        return -1;
    }
    if (get_provider_type("apple") != PROVIDER_APPLE) {
        printf("FAIL: apple should return PROVIDER_APPLE\n");
        return -1;
    }
    
    // Test invalid providers
    if (get_provider_type("invalid") != PROVIDER_UNKNOWN) {
        printf("FAIL: invalid should return PROVIDER_UNKNOWN\n");
        return -1;
    }
    if (get_provider_type("") != PROVIDER_UNKNOWN) {
        printf("FAIL: empty string should return PROVIDER_UNKNOWN\n");
        return -1;
    }
    if (get_provider_type(NULL) != PROVIDER_UNKNOWN) {
        printf("FAIL: NULL should return PROVIDER_UNKNOWN\n");
        return -1;
    }
    
    printf("PASS: get_provider_type tests\n");
    return 0;
}

// Test get_provider_config function
int test_get_provider_config() {
    printf("\n=== Testing get_provider_config ===\n");
    
    // Test valid provider configurations
    const ProviderConfig* google_config = get_provider_config(PROVIDER_GOOGLE);
    if (!google_config) {
        printf("FAIL: google config should not be NULL\n");
        return -1;
    }
    if (strcmp(google_config->name, "google") != 0) {
        printf("FAIL: google config name should be 'google'\n");
        return -1;
    }
    if (google_config->supported != 1) {
        printf("FAIL: google should be supported\n");
        return -1;
    }
    
    const ProviderConfig* github_config = get_provider_config(PROVIDER_GITHUB);
    if (!github_config) {
        printf("FAIL: github config should not be NULL\n");
        return -1;
    }
    if (strcmp(github_config->name, "github") != 0) {
        printf("FAIL: github config name should be 'github'\n");
        return -1;
    }
    if (github_config->supported != 0) {
        printf("FAIL: github should not be supported\n");
        return -1;
    }
    
    // Test invalid provider
    if (get_provider_config(PROVIDER_UNKNOWN) != NULL) {
        printf("FAIL: unknown provider should return NULL\n");
        return -1;
    }
    
    printf("PASS: get_provider_config tests\n");
    return 0;
}

// Test get_jwt_error_message function
int test_get_jwt_error_message() {
    printf("\n=== Testing get_jwt_error_message ===\n");
    
    if (strcmp(get_jwt_error_message(JWT_ERROR_NONE), "No error") != 0) {
        printf("FAIL: JWT_ERROR_NONE message incorrect\n");
        return -1;
    }
    if (strcmp(get_jwt_error_message(JWT_ERROR_INVALID_FORMAT), "Invalid JWT format") != 0) {
        printf("FAIL: JWT_ERROR_INVALID_FORMAT message incorrect\n");
        return -1;
    }
    if (strcmp(get_jwt_error_message(JWT_ERROR_EXPIRED), "JWT token has expired") != 0) {
        printf("FAIL: JWT_ERROR_EXPIRED message incorrect\n");
        return -1;
    }
    
    printf("PASS: get_jwt_error_message tests\n");
    return 0;
}

// Test base64url_decode function
int test_base64url_decode() {
    printf("\n=== Testing base64url_decode ===\n");
    
    // Test valid Base64 URL encoding
    const char* input = "SGVsbG8gV29ybGQ";
    uint8_t output[32];
    int output_len = 32;
    
    if (base64url_decode(input, output, &output_len) != 0) {
        printf("FAIL: base64url_decode should succeed for valid input\n");
        return -1;
    }
    if (output_len != 11) {
        printf("FAIL: output length should be 11, got %d\n", output_len);
        return -1;
    }
    
    // Verify decoded result
    if (strncmp((char*)output, "Hello World", 11) != 0) {
        printf("FAIL: decoded content incorrect\n");
        return -1;
    }
    
    // Test invalid input
    const char* invalid_input = "Invalid!@#";
    output_len = 32;
    if (base64url_decode(invalid_input, output, &output_len) == 0) {
        printf("FAIL: base64url_decode should fail for invalid input\n");
        return -1;
    }
    
    printf("PASS: base64url_decode tests\n");
    return 0;
}

// Test JWT decode functionality
int test_jwt_decode() {
    printf("\n=== Testing JWT Decode ===\n");
    
    // Test JWT token
    const char* test_jwt = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjA3ZjA3OGYyNjQ3ZThjZDAxOWM0MGRhOTU2OWU0ZjUyNDc5OTEwOTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiI1NjA2MjkzNjU1MTctbXQ5ajlhcmZsY2dpMzVpOGhwb3B0cjY2cWdvMWxtZm0uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiI1NjA2MjkzNjU1MTctbXQ5ajlhcmZsY2dpMzVpOGhwb3B0cjY2cWdvMWxtZm0uYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMTExNDA0NjE1MzAyNDYxNjQ1MjYiLCJub25jZSI6InlwanZ6TXB6d09qelcycUlrVnBiQU9UTUZuVSIsIm5iZiI6MTc1Nzc1MjA2NCwiaWF0IjoxNzU3NzUyMzY0LCJleHAiOjE3NTc3NTU5NjQsImp0aSI6ImZkYzRmNTc3YWI0NWViZjhiMjU3NjkwMjQwZmUzMTYyOGFkOGI4ZmMifQ.D4NVKogzU76ZGV5HsUDTOHRwSSG1I3lgG4bUEWAeMW8G-QDnXBNY6QDFmYnVEWWx5VlejyQhvmdtJrXF2eDOMKGeOwnFlm1INQuneELbLz0sbKnDw62IKshgQGNP5jv5ij-HEKj3jkx8D1zof83duVDhFOUmDud0VZKPODfBRLbqoTJKz0cp0RwZ5k-SiT_aSeL-y_FodYcCt5VtXIZfvgWj_NbcscqPaIBMvjJ9-wFx8yD-6C5dIQDVgyhZGtLzwxRLZMr6yotBuz_49BlKquuPA6TgNdUvMRu35QRYEQYPx3RigYtKw_8GGW-LVbmZTKSBOKu8QMEweR9CCaBHvg";
    
    // Test JWK
    const char* test_jwk_n = "pX0uFURVHarx3LZWaF4LnP3Kh2MbVl3iEOpQUcSxADEutXj383X9ZU6wdCmX4y_K23b0BU6oID1q0jkEE3sfQYaJJ7Qj9u2UnT-G9oGUoAn9GV1AYWxCNSz9mCrIJxP7ywcrvWJsKiYo7Q3Q-Tz44W1dCdVDQW870eixQSCnc6xrz4tu7RKrpeStH_GDhNIY3tXOuZvlPIvv4PH5sL39RaQ36T8ceGTWVDlYogKtvUUWl2YCGhz0f5y_ToRKU_WjnOmrN25_x30chCH3uz6I1RUa8vTAjbxCk4H5d1NmFNgV1zMSUKG0qo2d91fbyjmIRyODPVuUzSozREcVeSF_3Q";
    const char* test_jwk_e = "AQAB";
    const char* test_jwk_kid = "07f078f2647e8cd019c40da9569e4f5247991094";
    
    try {
        // 1. Test JWT decoding
        printf("[TEST] Decoding JWT token...\n");
        auto decoded = jwt::decode(std::string(test_jwt));
        
        // Verify header information
        printf("[TEST] JWT Header - kid: %s, alg: %s, typ: %s\n", 
               decoded.get_key_id().c_str(),
               decoded.get_algorithm().c_str(), 
               decoded.get_type().c_str());
        
        // Verify kid matches
        if (decoded.get_key_id() != test_jwk_kid) {
            printf("FAIL: JWT kid (%s) does not match expected kid (%s)\n", 
                   decoded.get_key_id().c_str(), test_jwk_kid);
            return -1;
        }
        
        // Verify algorithm
        if (decoded.get_algorithm() != "RS256") {
            printf("FAIL: JWT algorithm (%s) is not RS256\n", decoded.get_algorithm().c_str());
            return -1;
        }
        
        // Verify type
        if (decoded.get_type() != "JWT") {
            printf("FAIL: JWT type (%s) is not JWT\n", decoded.get_type().c_str());
            return -1;
        }
        
        // 2. Test payload decoding
        printf("[TEST] JWT Payload information:\n");
        printf("  iss: %s\n", decoded.get_issuer().c_str());
        printf("  sub: %s\n", decoded.get_subject().c_str());
        
        // Verify issuer
        if (decoded.get_issuer() != "https://accounts.google.com") {
            printf("FAIL: JWT issuer (%s) does not match expected issuer\n", decoded.get_issuer().c_str());
            return -1;
        }
        
        // Verify subject
        if (decoded.get_subject() != "111140461530246164526") {
            printf("FAIL: JWT subject (%s) does not match expected subject\n", decoded.get_subject().c_str());
            return -1;
        }
        
        // 3. Test JWK to PEM conversion
        printf("[TEST] Converting JWK to PEM format...\n");
        std::string pem_key = jwk_to_pem(test_jwk_n, test_jwk_e);
        if (pem_key.empty()) {
            printf("FAIL: Failed to convert JWK to PEM format\n");
            return -1;
        }
        printf("[TEST] JWK converted to PEM successfully\n");
        
        // 4. Test JWT verification (using manually provided JWK)
        printf("[TEST] Verifying JWT with manual JWK...\n");
        try {
            // Create RSA public key
            auto rsa_public_key = jwt::algorithm::rs256(pem_key, "", "", "");
            
            // Create verifier (skip expiration time validation by setting large leeway)
            auto verifier = jwt::verify()
                .with_issuer("https://accounts.google.com")
                .with_audience("560629365517-mt9j9arflcgi35i8hpoptr66qgo1lmfm.apps.googleusercontent.com")
                .allow_algorithm(rsa_public_key)
                .leeway(999999999);  // Very large leeway to effectively skip expiration check in test
            
            // Verify JWT
            verifier.verify(decoded);
            printf("[TEST] JWT signature verification successful!\n");
            
        } catch (const std::exception& e) {
            printf("FAIL: JWT verification failed: %s\n", e.what());
            return -1;
        }
        
        // 5. Test custom JWKS structure
        printf("[TEST] Testing custom JWKS structure...\n");
        JWKSResponse custom_jwks = {0};
        custom_jwks.keys = (JWKKey*)malloc(sizeof(JWKKey));
        custom_jwks.key_count = 1;
        
        // Initialize key
        custom_jwks.keys[0].kid = strdup(test_jwk_kid);
        custom_jwks.keys[0].n = strdup(test_jwk_n);
        custom_jwks.keys[0].e = strdup(test_jwk_e);
        custom_jwks.keys[0].alg = strdup("RS256");
        custom_jwks.keys[0].kty = strdup("RSA");
        custom_jwks.keys[0].use = strdup("sig");
        
        // Find matching key
        JWKKey* matching_key = NULL;
        std::string kid = decoded.get_key_id();
        for (int i = 0; i < custom_jwks.key_count; i++) {
            if (custom_jwks.keys[i].kid && kid == std::string(custom_jwks.keys[i].kid)) {
                matching_key = &custom_jwks.keys[i];
                break;
            }
        }
        
        if (!matching_key) {
            printf("FAIL: No matching key found in custom JWKS\n");
            free_jwks(&custom_jwks);
            return -1;
        }
        
        printf("[TEST] Found matching key in custom JWKS: kid=%s, alg=%s, kty=%s\n", 
               matching_key->kid, matching_key->alg, matching_key->kty);
        
        // Clean up resources
        free_jwks(&custom_jwks);
        
        printf("PASS: JWT decode tests\n");
        return 0;
        
    } catch (const std::exception& e) {
        printf("FAIL: JWT decode test failed: %s\n", e.what());
        return -1;
    }
}

// Run all tests
int run_all_tests() {
    printf("=== Running Unit Tests ===\n");
    
    int failed_tests = 0;
    
    if (test_get_provider_type() != 0) failed_tests++;
    if (test_get_provider_config() != 0) failed_tests++;
    if (test_get_jwt_error_message() != 0) failed_tests++;
    if (test_base64url_decode() != 0) failed_tests++;
    if (test_jwt_decode() != 0) failed_tests++;
    
    printf("\n=== Test Results ===\n");
    if (failed_tests == 0) {
        printf("All tests PASSED!\n");
        return 0;
    } else {
        printf("%d test(s) FAILED!\n", failed_tests);
        return -1;
    }
}
#endif

int main(int argc, char* argv[]) {
    printf("=== SGX JWT Salt Generator HTTP Server ===\n\n");
    
    // Check if test mode is enabled
    if (argc > 1 && strcmp(argv[1], "--test") == 0) {
        #ifdef TEST_MODE
        return run_all_tests();
        #else
        printf("Error: Test mode not enabled. Compile with -DTEST_MODE to enable tests.\n");
        return -1;
        #endif
    }
    
    // Set up signal handling
    signal(SIGINT, signal_handler);
    signal(SIGTERM, signal_handler);
    
    // Initialize CURL
    curl_global_init(CURL_GLOBAL_DEFAULT);
    
    // Initialize enclave
    if (initialize_enclave() < 0) {
        printf("Failed to initialize enclave\n");
        curl_global_cleanup();
        return -1;
    }
    
    // Start HTTP server
    if (start_http_server() < 0) {
        printf("Failed to start HTTP server\n");
        sgx_destroy_enclave(global_eid);
        curl_global_cleanup();
        return -1;
    }
    
    // Main loop - keep server running
    while (server_running) {
        sleep(1);
    }
    
    // Cleanup resources
    printf("\n[INFO] Shutting down...\n");
    if (http_daemon) {
        MHD_stop_daemon(http_daemon);
        http_daemon = NULL;
    }
    sgx_destroy_enclave(global_eid);
    curl_global_cleanup();
    
    printf("Enclave destroyed successfully!\n");
    return 0;
}