[package]
name = "Helloworldsampleenclave"
version = "1.0.0"
authors = ["The Teaclave Authors"]

[lib]
name = "helloworldsampleenclave"
crate-type = ["staticlib"]

[features]
default = []

[dependencies]
hkdf = "=0.12.3"  
sha2 = { version = "=0.10", default-features = false }
hex-literal = "0.4.1"
base64 = { version = "0.13", default-features = false, features = ["alloc"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }

[target.'cfg(not(target_env = "sgx"))'.dependencies]
# sgx_types = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
# sgx_tstd = { git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_types = { path = "/opt/teaclave-sgx-sdk/sgx_types" }
sgx_tstd =  { path = "/opt/teaclave-sgx-sdk/sgx_tstd" }