#include "Enclave.h"
#include "Enclave_t.h"  // Generated by edger8r
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <stdint.h>
#include "sgx_tcrypto.h"

// Declare printf function
int printf(const char* fmt, ...);

// Base64 decode function
static int base64_decode(const char* input, uint8_t* output, int* output_len) {
    const char* chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    int input_len = strlen(input);
    int i = 0, j = 0;
    int padding = 0;
    
    // Calculate padding
    if (input_len > 0 && input[input_len - 1] == '=') {
        padding++;
        if (input_len > 1 && input[input_len - 2] == '=') {
            padding++;
        }
    }
    
    while (i < input_len) {
        if (input[i] == '=') break;
        
        uint32_t a = 0, b = 0, c = 0, d = 0;
        
        // Find character position in base64 table
        const char* pos_a = strchr(chars, input[i++]);
        const char* pos_b = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        const char* pos_c = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        const char* pos_d = (i < input_len) ? strchr(chars, input[i++]) : NULL;
        
        if (!pos_a || !pos_b) return -1;
        
        a = pos_a - chars;
        b = pos_b - chars;
        c = pos_c ? (pos_c - chars) : 0;
        d = pos_d ? (pos_d - chars) : 0;
        
        uint32_t combined = (a << 18) | (b << 12) | (c << 6) | d;
        
        if (j < *output_len) output[j++] = (combined >> 16) & 0xFF;
        if (j < *output_len && pos_c) output[j++] = (combined >> 8) & 0xFF;
        if (j < *output_len && pos_d) output[j++] = combined & 0xFF;
    }
    
    *output_len = j;
    return 0;
}

// Simple JSON parsing function - extract sub, iss, aud fields
static int parse_jwt_claims(const char* json_str, char* sub, char* iss, char* aud) {
    // This is a simplified JSON parser, only for extracting specific fields
    // In actual applications, a complete JSON library should be used
    
    const char* sub_start = strstr(json_str, "\"sub\":\"");
    const char* iss_start = strstr(json_str, "\"iss\":\"");
    const char* aud_start = strstr(json_str, "\"aud\":\"");
    
    if (!sub_start || !iss_start || !aud_start) {
        return -1;
    }
    
    // Extract sub
    sub_start += 7; // Skip "sub":"
    const char* sub_end = strchr(sub_start, '"');
    if (sub_end) {
        int len = sub_end - sub_start;
        if (len < 256) {
            strncpy(sub, sub_start, len);
            sub[len] = '\0';
        }
    }
    
    // Extract iss
    iss_start += 7; // Skip "iss":"
    const char* iss_end = strchr(iss_start, '"');
    if (iss_end) {
        int len = iss_end - iss_start;
        if (len < 256) {
            strncpy(iss, iss_start, len);
            iss[len] = '\0';
        }
    }
    
    // Extract aud
    aud_start += 7; // Skip "aud":"
    const char* aud_end = strchr(aud_start, '"');
    if (aud_end) {
        int len = aud_end - aud_start;
        if (len < 256) {
            strncpy(aud, aud_start, len);
            aud[len] = '\0';
        }
    }
    
    return 0;
}

// HKDF Extract phase - using SGX HMAC-SHA256
static int hkdf_extract(const uint8_t* salt, size_t salt_len,
                       const uint8_t* ikm, size_t ikm_len,
                       uint8_t* prk, size_t* prk_len) {
    sgx_status_t ret = sgx_hmac_sha256_msg(ikm, ikm_len, salt, salt_len, prk, SGX_HMAC256_MAC_SIZE);
    if (ret != SGX_SUCCESS) {
        return -1;
    }
    
    *prk_len = SGX_HMAC256_MAC_SIZE;
    return 0;
}

// HKDF Expand phase - using SGX HMAC-SHA256
static int hkdf_expand(const uint8_t* prk, size_t prk_len,
                       const uint8_t* info, size_t info_len,
                       uint8_t* okm, size_t okm_len) {
    sgx_hmac_state_handle_t hmac_handle = NULL;
    uint8_t prev[SGX_HMAC256_MAC_SIZE];
    size_t done_len = 0;
    size_t dig_len = SGX_HMAC256_MAC_SIZE;
    size_t n = (okm_len + dig_len - 1) / dig_len; // Round up
    
    if (n > 255 || okm == NULL) {
        return -1;
    }
    
    for (size_t i = 1; i <= n; i++) {
        size_t copy_len;
        const uint8_t ctr = (uint8_t)i;
        
        // Initialize HMAC
        if (sgx_hmac256_init(prk, prk_len, &hmac_handle) != SGX_SUCCESS) {
            return -1;
        }
        
        // If not first iteration, add previous result
        if (i > 1) {
            if (sgx_hmac256_update(prev, dig_len, hmac_handle) != SGX_SUCCESS) {
                sgx_hmac256_close(hmac_handle);
                return -1;
            }
        }
        
        // Add info
        if (sgx_hmac256_update(info, info_len, hmac_handle) != SGX_SUCCESS) {
            sgx_hmac256_close(hmac_handle);
            return -1;
        }
        
        // Add counter
        if (sgx_hmac256_update(&ctr, 1, hmac_handle) != SGX_SUCCESS) {
            sgx_hmac256_close(hmac_handle);
            return -1;
        }
        
        // Get result
        if (sgx_hmac256_final(prev, dig_len, hmac_handle) != SGX_SUCCESS) {
            sgx_hmac256_close(hmac_handle);
            return -1;
        }
        
        // Close HMAC
        sgx_hmac256_close(hmac_handle);
        
        // Copy to output
        copy_len = (done_len + dig_len > okm_len) ? (okm_len - done_len) : dig_len;
        memcpy(okm + done_len, prev, copy_len);
        done_len += copy_len;
    }
    
    // Cleanup
    memset(prev, 0, sizeof(prev));
    
    return 0;
}

// Complete HKDF implementation
static int hkdf(const uint8_t* salt, size_t salt_len,
                const uint8_t* ikm, size_t ikm_len,
                const uint8_t* info, size_t info_len,
                uint8_t* okm, size_t okm_len) {
    uint8_t prk[SGX_HMAC256_MAC_SIZE];
    size_t prk_len;
    
    // Extract phase
    if (hkdf_extract(salt, salt_len, ikm, ikm_len, prk, &prk_len) != 0) {
        return -1;
    }
    
    // Expand phase
    int result = hkdf_expand(prk, prk_len, info, info_len, okm, okm_len);
    
    // Cleanup PRK
    memset(prk, 0, sizeof(prk));
    
    return result;
}

// Implement JWT to salt conversion
sgx_status_t jwt_to_salt(const uint8_t* some_string, size_t len, uint8_t* output_salt) {
    printf("[ECALL] Processing jwt_to_salt...\n");
    
    // Convert input to string
    char* input_str = (char*)malloc(len + 1);
    if (!input_str) {
        return SGX_ERROR_OUT_OF_MEMORY;
    }
    
    memcpy(input_str, some_string, len);
    input_str[len] = '\0';
    
    // Split JWT
    char* token = strtok(input_str, ".");
    if (!token) {
        free(input_str);
        return SGX_ERROR_INVALID_PARAMETER;
    }
    
    // Skip header, get payload
    token = strtok(NULL, ".");
    if (!token) {
        free(input_str);
        return SGX_ERROR_INVALID_PARAMETER;
    }
    
    // Base64 decode payload
    uint8_t* payload = (uint8_t*)malloc(len);
    int payload_len = len;
    
    if (base64_decode(token, payload, &payload_len) != 0) {
        free(input_str);
        free(payload);
        return SGX_ERROR_INVALID_PARAMETER;
    }
    
    // Parse JSON claims
    char sub[256] = {0};
    char iss[256] = {0};
    char aud[256] = {0};
    
    char* payload_str = (char*)malloc(payload_len + 1);
    memcpy(payload_str, payload, payload_len);
    payload_str[payload_len] = '\0';
    
    if (parse_jwt_claims(payload_str, sub, iss, aud) != 0) {
        free(input_str);
        free(payload);
        free(payload_str);
        return SGX_ERROR_INVALID_PARAMETER;
    }
    
    printf("[ECALL] JWT claims - sub: %s, iss: %s, aud: %s\n", sub, iss, aud);
    
    // Generate HKDF salt - combine iss and aud as salt
    char salt_str[512];
    snprintf(salt_str, sizeof(salt_str), "%s%s", iss, aud);
    
    // Use fixed IKM (in actual applications should use more secure method)
    uint8_t ikm[22];
    memset(ikm, 0x0b, sizeof(ikm));
    
    // Use complete HKDF implementation
    if (hkdf((uint8_t*)salt_str, strlen(salt_str),  // salt
             ikm, sizeof(ikm),                      // ikm
             (uint8_t*)sub, strlen(sub),            // info
             output_salt, 16) != 0) {               // output
        printf("[ERROR] HKDF generation failed\n");
        free(input_str);
        free(payload);
        free(payload_str);
        return SGX_ERROR_UNEXPECTED;
    }
    
    printf("[ECALL] Generated salt: ");
    for (int i = 0; i < 16; i++) {
        printf("%02x", output_salt[i]);
    }
    printf("\n");
    
    free(input_str);
    free(payload);
    free(payload_str);
    
    return SGX_SUCCESS;
}

// Implement printf inside enclave
int printf(const char* fmt, ...) {
    char buf[1024] = {0};
    va_list ap;
    va_start(ap, fmt);
    vsnprintf(buf, sizeof(buf), fmt, ap);
    va_end(ap);
    ocall_print_message(buf);
    return (int)strlen(buf);
}