[dependencies]
alloc = {}

[dependencies.sgx_types]
path = "/opt/teaclave-sgx-sdk/sgx_types"
stage = 1

[dependencies.sgx_alloc]
path = "/opt/teaclave-sgx-sdk/sgx_alloc"
stage = 1

[dependencies.sgx_unwind]
path = "/opt/teaclave-sgx-sdk/sgx_unwind"
stage = 1

[dependencies.sgx_demangle]
path = "/opt/teaclave-sgx-sdk/sgx_demangle"
stage = 1

[dependencies.panic_abort]
path = "/opt/teaclave-sgx-sdk/rustlib/panic_abort"
stage = 1

[dependencies.sgx_libc]
path = "/opt/teaclave-sgx-sdk/sgx_libc"
stage = 2

[dependencies.sgx_tkey_exchange]
path = "/opt/teaclave-sgx-sdk/sgx_key_exchange/tkey_exchange"
stage = 2

[dependencies.sgx_tse]
path = "/opt/teaclave-sgx-sdk/sgx_tse"
stage = 2

[dependencies.sgx_crypto]
path = "/opt/teaclave-sgx-sdk/sgx_crypto"
stage = 2

[dependencies.sgx_trts]
path = "/opt/teaclave-sgx-sdk/sgx_trts"
stage = 3

[dependencies.sgx_backtrace_sys]
path = "/opt/teaclave-sgx-sdk/sgx_backtrace/sgx_backtrace_sys"
stage = 3

[dependencies.panic_unwind]
path = "/opt/teaclave-sgx-sdk/rustlib/panic_unwind"
stage = 3

[dependencies.sgx_tdh]
path = "/opt/teaclave-sgx-sdk/sgx_tdh"
stage = 4

[dependencies.sgx_tseal]
path = "/opt/teaclave-sgx-sdk/sgx_tseal"
stage = 4

[dependencies.sgx_tprotected_fs]
path = "/opt/teaclave-sgx-sdk/sgx_protected_fs/tfs"
stage = 4

[dependencies.sgx_tstd]
path = "/opt/teaclave-sgx-sdk/sgx_tstd"
stage = 5
features = ["backtrace"]

[dependencies.sgx_no_tstd]
path = "/opt/teaclave-sgx-sdk/sgx_no_tstd"
stage = 5

[dependencies.sgx_rand]
path = "/opt/teaclave-sgx-sdk/sgx_rand"
stage = 6

[dependencies.sgx_serialize]
path = "/opt/teaclave-sgx-sdk/sgx_serialize"
stage = 6

[dependencies.sgx_unit_test]
path = "/opt/teaclave-sgx-sdk/sgx_tests/unit"
stage = 6

[dependencies.sgx_backtrace]
path = "/opt/teaclave-sgx-sdk/sgx_backtrace"
stage = 7

[dependencies.sgx_cov]
path = "/opt/teaclave-sgx-sdk/sgx_tests/cov"
stage = 7